version: '3'

networks:
    rs-service-dev:

services:
    nginx_rs_dev:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - "8103:80"
        links:
            - php_rs_dev
        volumes:
            - ./:/var/www/html
            - ~/Program/Dev/rs-service/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ~/Program/Dev/rs-service/docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php_rs_dev
            - postgres_rs_dev
        networks:
            - rs-service-dev
    php_rs_dev:
        image: ${APP_IMAGE_DEV}:${APP_IMAGE_DEV_TAG}
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        volumes:
            - ~/Program/Dev/rs-service/storage:/var/www/html/storage:rw
            - ~/Program/Dev/rs-service/.env:/var/www/html/.env:rw
        networks:
            - rs-service-dev
    postgres_rs_dev:
        image: postgres:14.2-alpine
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        ports:
            - "5335:5432"
        volumes:
            - ~/Program/Dev/rs-service/docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        networks:
            - rs-service-dev