version: '3'

networks:
    rs-service-prod:

services:
    nginx_rs_prod:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        ports:
            - "8003:80"
        links:
            - phprsprod
        volumes:
            - ~/Program/rs-service/docker/nginx/site-prod.conf:/etc/nginx/conf.d/default.conf:rw
            - ~/Program/rs-service/docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - phprsprod
            - postgres_rs_prod
        networks:
            - rs-service-prod
    phprsprod:
        image: ${APP_IMAGE_PROD}:${APP_IMAGE_PROD_TAG}
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        ports:
            - "9864:9000"
        volumes:
            - ~/Program/rs-service/storage:/var/www/html/storage:rw
            - ~/Program/rs-service/.env:/var/www/html/.env:rw
        networks:
            - rs-service-prod
    postgres_rs_prod:
        image: postgres:14.2-alpine
        container_name: ${APP_NAME}_postgres
        restart: unless-stopped
        ports:
            - "5435:5432"
        volumes:
            - ~/Program/rs-service/docker/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: "trust"
        networks:
            - rs-service-prod
